export const CARD_ADD_ITEM = 'CARD_ADD_ITEM'
export const CARD_LIST_REQUEST = 'CARD_LIST_REQUEST'
export const CARD_LIST_SUCCESS = 'CARD_LIST_SUCCESS'
export const CARD_LIST_FAIL = 'CARD_LIST_FAIL'

export const CARD_DETAILS_REQUEST = 'CARD_DETAILS_REQUEST'
export const CARD_DETAILS_SUCCESS = 'CARD_DETAILS_SUCCESS'
export const CARD_DETAILS_FAIL = 'CARD_DETAILS_FAIL'

export const CARD_DELETE_REQUEST = 'CARD_DELETE_FAIL'
export const CARD_DELETE_SUCCESS = 'CARD_DELETE_SUCCESS'
export const CARD_DELETE_FAIL = 'CARD_DELETE_FAIL'
