export const DECK_LIST_REQUEST = 'DECK_LIST_REQUEST'
export const DECK_LIST_SUCCESS = 'DECK_LIST_SUCCESS'
export const DECK_LIST_FAIL = 'DECK_LIST_FAIL'
export const DECK_DETAILS_REQUEST = 'DECK_DETAILS_REQUEST'
export const DECK_DETAILS_SUCCESS = 'DECK_DETAILS_SUCCESS'
export const DECK_DETAILS_FAIL = 'DECK_DETAILS_FAIL'
export const DECK_CARDS_SUCCESS = 'DECK_CARDS_SUCCESS'
export const RESET_STATE = 'RESET_STATE'

export const DECK_UPDATE_REQUEST = 'DECK_UPDATE_REQUEST'
export const DECK_UPDATE_SUCCESS = 'DECK_UPDATE_SUCCESS'
export const DECK_UPDATE_FAIL = 'DECK_UPDATE_FAIL'


export const DECK_CREATE_REQUEST = 'DECK_CREATE_REQUEST'
export const DECK_CREATE_SUCCESS = 'DECK_CREATE_SUCCESS'
export const DECK_CREATE_FAIL = 'DECK_CREATE_FAIL'

export const DECK_DELETE_REQUEST = 'DECK_DELETE_REQUEST';
export const DECK_DELETE_SUCCESS = 'DECK_DELETE_SUCCESS';
export const DECK_DELETE_FAIL = 'DECK_DELETE_FAIL';


export const CARD_ADD_ITEM = 'CARD_ADD_ITEM'
export const CARD_REMOVE_ITEM = 'CARD_REMOVE_ITEM'
export const DECK_EMPTY = 'DECK_EMPTY';


// export const DECK_DELETE_RESET = 'DECK_DELETE_RESET';

